#
# This is for building a local OpenEMR development and testing environment.
# (Recommend not running it from your git repo and instead mirroring your
#  git repo to a testing directory (such as your web directory).)
#
# Brief instructions on how to use (for fuller instructions and examples,
#  see the document at contrib/util/docker/README.md):
#   1. docker-compose up -d
#   2. http://localhost:8080 to run setup in openemr (alpine 3.7 with PHP 7.1)
#      or
#      https://localhost:8090 to run setup in openemr with SSL (alpine 3.7 with PHP 7.1)
#      or
#      http://localhost:8081 to run setup in openemr (alpine edge with PHP 7.2)
#      or
#      https://localhost:8091 to run setup in openemr with SSL (alpine edge with PHP 7.2)
#  On the main setup input screen:
#   1. for Server Host, use either 'mariadb' or 'mysql' or `mariadb-dev` or 'mysql-dev' (have both mariadb/mysql/mariadb-dev/mysql-dev dockers ready to go make testing either one easy; mysql is version 5.7; mysql-dev is version 8; mariadb is version 10.2 and mariadb-dev is version 10.3)
#   2. for Root Pass, use 'root'
#   3. for User Hostname, use '%'
#  And when need to tear it down and restart it
#   1. docker-compose down -v
#   2. docker-compose up -d
#  Can see databases via http://localhost:8100
#
version: '3.1'
services:
  mysql:
    restart: always
    image: mysql:5.7
    command: ['mysqld','--character-set-server=utf8']
    environment:
      MYSQL_ROOT_PASSWORD: root
  mariadb-dev:
    restart: always
    image: mariadb:10.3
    command: ['mysqld','--character-set-server=utf8']
    environment:
      MYSQL_ROOT_PASSWORD: root
  mysql-dev:
    restart: always
    image: mysql:8
    command: ['mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
<<<<<<< HEAD
    - 3307:3306
  openemr:
    restart: always
    container_name: openemr_local_development 
    build: ./contrib/util/docker
    ports:
<<<<<<< HEAD
    - 8080:80
    - 8081:443
    volumes:
    - .:/var/www/localhost/htdocs/openemr
=======
    - 8101:80
    environment:
      PMA_HOST: mysql
  phpmyadmin-mariadb-dev:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
    - 8102:80
    environment:
      PMA_HOST: mariadb-dev
  phpmyadmin-mysql-dev:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
    - 8103:80
    environment:
      PMA_HOST: mysql-dev
=======
    - 8100:80
    environment:
      PMA_HOSTS: mariadb,mysql,mariadb-dev,mysql-dev
>>>>>>> decreased development dockers overhead by just using one phpmyadmin docker
  couchdb:
    restart: always
    image: couchdb
<<<<<<< HEAD
>>>>>>> also added mariadb-dev docker for future mariadb version testing
=======
    ports:
    - 5984:5984
    - 6984:6984
>>>>>>> added additional testing support for couchdb docker in dev environment
    environment:
<<<<<<< HEAD
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: wtr&5YU
      MYSQL_USER: derek
      MYSQL_PASS: Qa@er5t
      OE_USER: admin
      OE_PASS: pass
      #DOMAIN: emr.capitalspeechpath.com
      #EMAIL: dhillison@gmail.com
    links:
    - mysql
=======
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
  orthanc:
    restart: always
    image: jodogne/orthanc-plugins
    ports:
    - 4242:4242
    - 8042:8042
>>>>>>> added orthanc docker to docker development environment (#1642)
